
-------- 테이블 생성 --------

-------- MEMBER TABLE --------
CREATE TABLE TBL_MEMBER (
  MEMBER_ID       VARCHAR2(40)            NOT NULL,
  NAME            VARCHAR2(30)            NOT NULL,
  MOBILE_PHONE    VARCHAR2(100)           NOT NULL,
  PASSWORD        VARCHAR2(200)           NOT NULL,
  EMAIL           VARCHAR2(200)           NOT NULL,
  BIRTH_DATE      VARCHAR2(10)            NOT NULL,
  GENDER          NUMBER(1)               NOT NULL, 
  CREATED_AT      DATE DEFAULT SYSDATE    NOT NULL,
  STATUS          NUMBER(1)               NOT NULL,
  IDLE            NUMBER(1)               NOT NULL,

  CONSTRAINT PK_TBL_MEMBER_MEMBER_ID PRIMARY KEY (MEMBER_ID),
  CONSTRAINT CK_TBL_MEMBER_GENDER CHECK (GENDER IN (0,1)),
  CONSTRAINT CK_TBL_MEMBER_STATUS CHECK (STATUS IN (0,1)),
  CONSTRAINT CK_TBL_MEMBER_IDLE CHECK (IDLE IN (0,1)),
  CONSTRAINT UQ_TBL_MEMBER_EMAIL UNIQUE (EMAIL),
  CONSTRAINT UQ_TBL_MEMBER_MOBILE_PHONE UNIQUE (MOBILE_PHONE)
);


-------- PRODUCT TABLE --------
CREATE TABLE TBL_PRODUCT (
  PRODUCT_CODE  VARCHAR2(20)    NOT NULL,
  PRODUCT_NAME  VARCHAR2(100)   NOT NULL,
  BRAND_NAME    VARCHAR2(50)    NOT NULL,
  PRODUCT_DESC  VARCHAR2(1000)  NOT NULL,
  SALE_STATUS   VARCHAR2(20)    NOT NULL,

  CONSTRAINT PK_TBL_PRODUCT_PRODUCT_CODE PRIMARY KEY (PRODUCT_CODE)
);


-------- COUPON TABLE --------
CREATE TABLE TBL_COUPON (
  COUPON_CATEGORY_NO NUMBER                  NOT NULL,
  COUPON_NAME        VARCHAR2(20)            NOT NULL,
  DISCOUNT_VALUE     NUMBER                  NOT NULL,
  DISCOUNT_TYPE      NUMBER(1)               NOT NULL,  
  USABLE             NUMBER(1) DEFAULT 1     NOT NULL, 

  CONSTRAINT PK_TBL_COUPON_COUPON_CATEGORY_NO PRIMARY KEY (COUPON_CATEGORY_NO),
  CONSTRAINT CK_TBL_COUPON_DISCOUNT_TYPE CHECK (DISCOUNT_TYPE IN (0,1)),
  CONSTRAINT CK_TBL_COUPON_USABLE CHECK (USABLE IN (0,1)),
  CONSTRAINT CK_TBL_COUPON_DISCOUNT_VALUE CHECK (DISCOUNT_VALUE > 0)
);

-------- 시퀀스 생성 --------

CREATE SEQUENCE SEQ_TBL_COUPON_COUPON_CATEGORY_NO
START WITH 1 INCREMENT BY 1 NOCACHE NOCYCLE;


-------- PRODUCT_OPTION TABLE --------
CREATE TABLE TBL_PRODUCT_OPTION (
  OPTION_ID             NUMBER         NOT NULL,
  FK_PRODUCT_CODE       VARCHAR2(20)   NOT NULL,
  COLOR                 VARCHAR2(20)   NOT NULL,
  STORAGE_SIZE          VARCHAR2(20)   NOT NULL,
  PRICE                 NUMBER         NOT NULL,
  STOCK_QTY             NUMBER         NOT NULL,
  IMAGE_PATH            VARCHAR2(200)  NOT NULL,

  CONSTRAINT PK_TBL_PRODUCT_OPTION_OPTION_ID PRIMARY KEY (OPTION_ID),
  CONSTRAINT FK_TBL_PRODUCT_OPTION_FK_PRODUCT_CODE FOREIGN KEY (FK_PRODUCT_CODE)
  REFERENCES TBL_PRODUCT (PRODUCT_CODE),
  CONSTRAINT CK_TBL_PRODUCT_OPTION_PRICE CHECK (PRICE > 0),
  CONSTRAINT CK_TBL_PRODUCT_OPTION_STOCK_QTY CHECK (STOCK_QTY >= 0),
  CONSTRAINT UQ_TBL_PRODUCT_OPTION_FK_PRODUCT_CODE_COLOR_STORAGE_SIZE UNIQUE (FK_PRODUCT_CODE, COLOR, STORAGE_SIZE)
);


-------- 시퀀스 생성 --------

CREATE SEQUENCE SEQ_TBL_PRODUCT_OPTION_OPTION_ID
START WITH 1 INCREMENT BY 1 NOCACHE NOCYCLE; 


-------- COUPON_ISSUE TABLE --------
CREATE TABLE TBL_COUPON_ISSUE (
  FK_COUPON_CATEGORY_NO         NUMBER                  NOT NULL,
  COUPON_ID                     NUMBER                  NOT NULL,  
  FK_MEMBER_ID                  VARCHAR2(40)            NOT NULL,
  ISSUE_DATE                    DATE DEFAULT SYSDATE    NOT NULL,
  EXPIRE_DATE                   DATE                    NOT NULL,
  USED_YN                       NUMBER(1) DEFAULT 0     NOT NULL, 

  CONSTRAINT PK_TBL_COUPON_ISSUE_FK_COUPON_CATEGORY_NO_COUPON_ID PRIMARY KEY (FK_COUPON_CATEGORY_NO, COUPON_ID),
  CONSTRAINT FK_TBL_COUPON_ISSUE_FK_COUPON_CATEGORY_NO FOREIGN KEY (FK_COUPON_CATEGORY_NO)
  REFERENCES TBL_COUPON (COUPON_CATEGORY_NO),
  CONSTRAINT FK_TBL_COUPON_ISSUE_FK_MEMBER_ID FOREIGN KEY (FK_MEMBER_ID)
  REFERENCES TBL_MEMBER (MEMBER_ID),
  CONSTRAINT CK_TBL_COUPON_ISSUE_USED_YN CHECK (USED_YN IN (0,1)),
  CONSTRAINT CK_TBL_COUPON_ISSUE_EXPIRE_DATE CHECK (EXPIRE_DATE > ISSUE_DATE)
);


-------- DELIVERY TABLE --------
CREATE TABLE TBL_DELIVERY (
  DELIVERY_ADDRESS_ID   NUMBER                NOT NULL,
  FK_MEMBER_ID          VARCHAR2(40)          NOT NULL,
  RECIPIENT_NAME        VARCHAR2(50)          NOT NULL,
  RECIPIENT_PHONE       VARCHAR2(100)         NOT NULL,
  ADDRESS               VARCHAR2(200)         NOT NULL,
  ADDRESS_DETAIL        VARCHAR2(200)         NOT NULL,
  ADDRESS_EXTRA         VARCHAR2(200)                 , 
  IS_DEFAULT            NUMBER(1) DEFAULT 0   NOT NULL,
  POSTAL_CODE           VARCHAR2(50)          NOT NULL, 

  CONSTRAINT PK_TBL_DELIVERY_DELIVERY_ADDRESS_ID PRIMARY KEY (DELIVERY_ADDRESS_ID),
  CONSTRAINT FK_TBL_DELIVERY_FK_MEMBER_ID FOREIGN KEY (FK_MEMBER_ID)
  REFERENCES TBL_MEMBER (MEMBER_ID),
  CONSTRAINT CK_TBL_DELIVERY_IS_DEFAULT CHECK (IS_DEFAULT IN (0,1))
);

-------- 시퀀스 생성 --------

CREATE SEQUENCE SEQ_TBL_DELIVERY_DELIVERY_ADDRESS_ID
START WITH 1 INCREMENT BY 1 NOCACHE NOCYCLE;


-------- CART TABLE --------
CREATE TABLE TBL_CART (
  CART_ID         NUMBER                      NOT NULL,
  FK_MEMBER_ID    VARCHAR2(40)                NOT NULL,
  FK_OPTION_ID    NUMBER                      NOT NULL,
  ADDED_DATE      DATE    DEFAULT SYSDATE     NOT NULL,
  QUANTITY        NUMBER                      NOT NULL,

  CONSTRAINT PK_TBL_CART_CART_ID PRIMARY KEY (CART_ID),
  CONSTRAINT FK_TBL_CART_FK_MEMBER_ID FOREIGN KEY (FK_MEMBER_ID)
  REFERENCES TBL_MEMBER (MEMBER_ID),
  CONSTRAINT FK_TBL_CART_FK_OPTION_ID FOREIGN KEY (FK_OPTION_ID)
  REFERENCES TBL_PRODUCT_OPTION (OPTION_ID),
  CONSTRAINT CK_TBL_CART_QUANTITY CHECK (QUANTITY > 0),
  CONSTRAINT UQ_TBL_CART_FK_MEMBER_ID_FK_OPTION_ID UNIQUE (FK_MEMBER_ID, FK_OPTION_ID)
);

-------- 시퀀스 생성 --------

CREATE SEQUENCE SEQ_TBL_CART_CART_ID
START WITH 1 INCREMENT BY 1 NOCACHE NOCYCLE;


-------- ORDERS TABLE --------
CREATE TABLE TBL_ORDERS (
  ORDER_ID               NUMBER                     NOT NULL,
  FK_MEMBER_ID           VARCHAR2(40)               NOT NULL,
  ORDER_DATE             DATE DEFAULT SYSDATE       NOT NULL,
  TOTAL_AMOUNT           NUMBER                     NOT NULL,
  DISCOUNT_AMOUNT        NUMBER                     NOT NULL,
  ORDER_STATUS           VARCHAR2(20)               NOT NULL,
  DELIVERY_ADDRESS       VARCHAR2(300)              NOT NULL,

  CONSTRAINT PK_TBL_ORDERS_ORDER_ID PRIMARY KEY (ORDER_ID),
  CONSTRAINT FK_TBL_ORDERS_FK_MEMBER_ID FOREIGN KEY (FK_MEMBER_ID)
  REFERENCES TBL_MEMBER (MEMBER_ID),
  CONSTRAINT CK_TBL_ORDERS_TOTAL_AMOUNT CHECK (TOTAL_AMOUNT > 0),
  CONSTRAINT CK_TBL_ORDERS_DISCOUNT_AMOUNT CHECK (
    DISCOUNT_AMOUNT >= 0 AND DISCOUNT_AMOUNT < TOTAL_AMOUNT
  )
);

-------- 시퀀스 생성 --------

CREATE SEQUENCE SEQ_TBL_ORDERS_ORDER_ID
START WITH 1 INCREMENT BY 1 NOCACHE NOCYCLE;


-------- ORDER_DETAIL TABLE --------
CREATE TABLE TBL_ORDER_DETAIL (
  ORDER_DETAIL_ID       NUMBER                   NOT NULL,
  FK_OPTION_ID          NUMBER                   NOT NULL,
  FK_ORDER_ID           NUMBER                   NOT NULL,
  QUANTITY              NUMBER                   NOT NULL,
  UNIT_PRICE            NUMBER                   NOT NULL,
  IS_REVIEW_WRITTEN     NUMBER(1) DEFAULT 0      NOT NULL, 
  PRODUCT_NAME          VARCHAR2(100)            NOT NULL,
  BRAND_NAME            VARCHAR2(50)             NOT NULL,

  CONSTRAINT PK_TBL_ORDER_DETAIL_ORDER_DETAIL_ID PRIMARY KEY (ORDER_DETAIL_ID),
  CONSTRAINT FK_TBL_ORDER_DETAIL_FK_OPTION_ID FOREIGN KEY (FK_OPTION_ID)
  REFERENCES TBL_PRODUCT_OPTION (OPTION_ID),
  CONSTRAINT FK_TBL_ORDER_DETAIL_FK_ORDER_ID FOREIGN KEY (FK_ORDER_ID)
  REFERENCES TBL_ORDERS (ORDER_ID),
  CONSTRAINT CK_TBL_ORDER_DETAIL_QUANTITY CHECK (QUANTITY > 0),
  CONSTRAINT CK_TBL_ORDER_DETAIL_UNIT_PRICE CHECK (UNIT_PRICE > 0),
  CONSTRAINT CK_TBL_ORDER_DETAIL_IS_REVIEW_WRITTEN CHECK (IS_REVIEW_WRITTEN IN (0,1))
);

-------- 시퀀스 생성 --------

CREATE SEQUENCE SEQ_TBL_ORDER_DETAIL_ORDER_DETAIL_ID
START WITH 1 INCREMENT BY 1 NOCACHE NOCYCLE;


-------- REVIEW TABLE --------
CREATE TABLE TBL_REVIEW (
  REVIEW_NUMBER         NUMBER                  NOT NULL,
  FK_OPTION_ID          NUMBER                  NOT NULL,
  FK_ORDER_DETAIL_ID    NUMBER                  NOT NULL,
  REVIEW_CONTENT        VARCHAR2(1000)          NOT NULL,
  WRITEDAY              DATE DEFAULT SYSDATE    NOT NULL,

  CONSTRAINT PK_TBL_REVIEW_REVIEW_NUMBER PRIMARY KEY (REVIEW_NUMBER),
  CONSTRAINT FK_TBL_REVIEW_FK_OPTION_ID FOREIGN KEY (FK_OPTION_ID)
  REFERENCES TBL_PRODUCT_OPTION (OPTION_ID),
  CONSTRAINT FK_TBL_REVIEW_FK_ORDER_DETAIL_ID FOREIGN KEY (FK_ORDER_DETAIL_ID)
  REFERENCES TBL_ORDER_DETAIL (ORDER_DETAIL_ID),
  CONSTRAINT UQ_TBL_REVIEW_FK_ORDER_DETAIL_ID UNIQUE (FK_ORDER_DETAIL_ID)
);

-------- 시퀀스 생성 --------

CREATE SEQUENCE SEQ_TBL_REVIEW_REVIEW_NUMBER
START WITH 1 INCREMENT BY 1 NOCACHE NOCYCLE;


-------- INQUIRY TABLE --------
CREATE TABLE TBL_INQUIRY (
  INQUIRY_NUMBER        NUMBER                     NOT NULL,
  FK_MEMBER_ID          VARCHAR2(40)               NOT NULL,
  INQUIRY_TYPE          VARCHAR2(30)               NOT NULL,
  TITLE                 VARCHAR2(100)              NOT NULL,
  REGISTERDAY           DATE DEFAULT SYSDATE       NOT NULL,
  INQUIRY_CONTENT       VARCHAR2(1000)             NOT NULL,
  REPLY_CONTENT         VARCHAR2(1000),
  REPLY_REGISTERDAY     DATE,                                         
  REPLY_STATUS          NUMBER(1) DEFAULT 0   NOT NULL, 

  CONSTRAINT PK_TBL_INQUIRY_INQUIRY_NUMBER PRIMARY KEY (INQUIRY_NUMBER),
  CONSTRAINT FK_TBL_INQUIRY_FK_MEMBER_ID FOREIGN KEY (FK_MEMBER_ID)
  REFERENCES TBL_MEMBER (MEMBER_ID),
  CONSTRAINT CK_TBL_INQUIRY_REPLY_STATUS CHECK (REPLY_STATUS IN (0,1))
);

-------- 시퀀스 생성 --------

CREATE SEQUENCE SEQ_TBL_INQUIRY_INQUIRY_NUMBER
START WITH 1 INCREMENT BY 1 NOCACHE NOCYCLE;


select * from tab;
select * from tbl_member;
select * from tbl_delivery;


select member_id
from tbl_member
where member_id = 'anth'; 
















